artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data_spaceShip.csv
  cloud_config_zipfile: secure-connect-spaceship-db3.zip
  authentication_token: spaceship_db3-token.json

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.pt

training:
  root_dir: artifacts/training
  checkpoint_model_filepath:  artifacts/prepare_callbacks/checkpoint_dir/model.pt
  trained_model_path: artifacts/training/model.pt
  encoder_traindata: artifacts/training/encoder_traindata.pickle
  onnx_model_path: artifacts/training/spaceship.onnx